### ISSUE TITLE
I get permission denied when I do bgctl show fib

### ISSUE THREAD

**Issue by ll-kang** [openbgpd-portable/openbgpd-portable#60] opened 2023-08-11 09:04 UTC
'm on ubuntu-22.04 using openbgpd-8.1, I'm stuck with a problem. When I do bgctl show fib I get permission denied，I found that it automatically loads the kroute-disabled.c. Then I downloaded libmnl using apt-get install -y libmnl-dev and I found that it automatically loads the kroute-linux.c, but bgpd cannot start. 
startup
PF_KEY not available, disabling ipsec
mnl_attr_validate for RTA_METRICS failed.
mnl_cb_run error
failed to load routing table 0
route decision engine ready
peer closed imsg connection
fatal in RDE: Lost connection to parent
session engine ready
rtr engine ready
peer closed imsg connection
peer closed imsg connection
fatal in RTR: Lost connection to parent
SE: Lost connection to parent
session engine exiting
terminating

I want to know which kroute file should I choose, kroute-linux.c or kroute.c or others，and what dependencies should I install like libmnl.

**Comment by cjeker** [comment] 2023-08-30 07:29
Duplicate of #61 

Without FIB support it is expected that `bgpctl show fib` returns an error. Maybe a better error message should be used.

**Closed by cjeker** 2023-08-30 07:29 UTC
