### ISSUE TITLE
Unexpected behaviours with 6.9p0 and 'rde evaluate all'

### ISSUE THREAD

**Issue by pierky** [openbgpd-portable/openbgpd-portable#21] opened 2021-05-01 15:39 UTC
Hello,

I'm observing a weird behaviour with 6.9p0 (portable) when the new `rde evaluate all` feature is set.

I'm using an integration test from ARouteServer to evaluate this feature: https://github.com/pierky/arouteserver/tree/master/tests/live_tests/scenarios/path_hiding

There are Docker containers representing some BGP speakers, one of them runs OpenBGPD 6.9p0.

AS1, AS2 and AS3 are clients of the route-server.

AS101 advertises 101.0.1.0/24 to AS1 and AS2, prepending 3 times to AS2.

Both AS1 and AS2 propagate that route to the route-server, but AS1 tags it with the BGP community '0:3', which means "do not announce to AS3" (see the `deny quick to 192.0.2.31 community 0:3` line in the config).

So, the route-server has the best path towards AS1, and a sub-optimal path (due to prepending by AS101) via AS2, but the best-route is also tagged in a way that prevents it from being exported to AS3.

In this scenario, with path hiding mitigation in place, I'd expect the route via AS1 to not being announced to AS3, but I'd also expect the sub-optimal path via AS2 to be.

The configuration that I'm using for the route-server can be found here: https://gist.github.com/pierky/c96d1defc5f8024ec76ae64f0b511fb2

What I observe follows.

- As soon as the containers come up, I see the routes being received by the route-server:

```
root@2fa54399f0d7:~# bgpctl show rib detail

BGP routing table entry for 101.0.1.0/24
    1 101
    Nexthop 192.0.2.11 (via 192.0.2.11) Neighbor 192.0.2.11 (192.0.2.11)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid, best
    Last update: 00:01:33 ago
    Communities: 0:3 0:4

BGP routing table entry for 101.0.1.0/24
    2 101 101 101 101
    Nexthop 192.0.2.21 (via 192.0.2.21) Neighbor 192.0.2.21 (192.0.2.21)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid
    Last update: 00:01:34 ago
```

The first thing that I see which goes against my expectations is that no routes are exported to 192.0.2.31, even though `rde evaluate all` is configured:

```
root@2fa54399f0d7:~# bgpctl show rib out neighbor 192.0.2.31
flags: * = Valid, > = Selected, I = via IBGP, A = Announced,
       S = Stale, E = Error
origin validation state: N = not-found, V = valid, ! = invalid
origin: i = IGP, e = EGP, ? = Incomplete

flags ovs destination          gateway          lpref   med aspath origin
```

- Even after a `bgpctl reload` no routes are exported to 192.0.2.31 yet.

- Then I stop the route-server container and I spin it up again; at that point, I see the expected route being exported to 192.0.2.31:

```
root@4a209fd23cf1:~# bgpctl show rib out neighbor 192.0.2.31
flags: * = Valid, > = Selected, I = via IBGP, A = Announced,
       S = Stale, E = Error
origin validation state: N = not-found, V = valid, ! = invalid
origin: i = IGP, e = EGP, ? = Incomplete

flags ovs destination          gateway          lpref   med aspath origin
*       N 101.0.1.0/24         192.0.2.21        100     0 2 101 101 101 101 i
```

The output of `bgpctl show rib detail` is unchanged, same as above.

- Finally, I shut down the BGP session between AS101 and AS2. The route-server sees the withdrawal of the 101_2 path:

```
Rib Loc-RIB: neighbor 192.0.2.21 AS2: withdraw 101.0.1.0/24
```

The path actually disappears from `bgpctl show rib detail`...

```
root@4a209fd23cf1:~# bgpctl show rib detail

BGP routing table entry for 101.0.1.0/24
    1 101
    Nexthop 192.0.2.11 (via 192.0.2.11) Neighbor 192.0.2.11 (192.0.2.11)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid, best
    Last update: 00:03:43 ago
    Communities: 0:3 0:4
```

... but not from the set of routes being announced to 192.0.2.31:

```
root@4a209fd23cf1:~# bgpctl show rib out neighbor 192.0.2.31
flags: * = Valid, > = Selected, I = via IBGP, A = Announced,
       S = Stale, E = Error
origin validation state: N = not-found, V = valid, ! = invalid
origin: i = IGP, e = EGP, ? = Incomplete

flags ovs destination          gateway          lpref   med aspath origin
*       N 101.0.1.0/24         192.0.2.21        100     0 2 101 101 101 101 i
```

AS3 (BIRD-based) still sees that route indeed:

```
bird> show route all
101.0.1.0/24       via 192.0.2.21 on eth0 [the_rs 14:54:14 from 192.0.2.2] * (100) [AS101i]
    Type: BGP unicast univ
    BGP.origin: IGP
    BGP.as_path: 2 101 101 101 101
    BGP.next_hop: 192.0.2.21
    BGP.local_pref: 100
```

A `bgpctl reload` doesn't solve the issue apparently:

```
rereading config
INTCOMM_PREF_OK_ROA = "soo 65535:1"
INTCOMM_ROUTE_OK_WL = "soo 65535:2"
INTCOMM_PREF_OK_ARINDB = "soo 65535:3"
INTCOMM_PREF_OK_REGISTROBRDB = "soo 65535:12"
INTCOMM_ORIGIN_OK = "soo 65535:4"
INTCOMM_ORIGIN_KO = "soo 65535:5"
INTCOMM_PREFIX_OK = "soo 65535:6"
INTCOMM_PREFIX_KO = "soo 65535:7"
INTCOMM_IRR_REJECT = "soo 65535:8"
INTCOMM_RPKI_UNKNOWN = "soo 65535:9"
INTCOMM_RPKI_INVALID = "soo 65535:10"
INTCOMM_RPKI_VALID = "soo 65535:11"
INTCOMM_NO_EXPORT = "soo 65535:65281"
INTCOMM_NO_ADVERTISE = "soo 65535:65282"
SE reconfigured
RTR engine reconfigured
RDE reconfigured
RDE soft reconfiguration done
```

`bgpctl show rib out neighbor 192.0.2.31` and `bgpctl show rib detail` output doesn't change after the reload.

- Only after `bgpctl neighbor 192.0.2.31 clear` the route disappears from `bgpctl show rib out neighbor 192.0.2.31` and is no longer received by AS3.

So, the anomalies I see are 2:

- initially the route is not exported to 192.0.2.31;

- the route is still announced even though it disappears from the RIB.

Am I missing anything? Can anyone else confirm these are unexpected behaviours?

Thanks

**Comment by cjeker** [comment] 2021-05-04 08:02
I managed to reproduce the withdraw issue and I sent a fix for that to tech@ mailing list.
I could not reproduce the issue with initially no announcements to the peer. Not sure what is going on there.

Could you enable 'log updates' and send me the `bgpd -dv` output. I wonder if the bug is in the nexthop validation.

**Comment by pierky** [comment] 2021-05-04 16:41
> I could not reproduce the issue with initially no announcements to the peer. Not sure what is going on there.
> 
> Could you enable 'log updates' and send me the `bgpd -dv` output. I wonder if the bug is in the nexthop validation.

I narrowed this specific part of the issue down a bit further: it seems that it happens only when `rde evaluate all` is enabled on an instance that is already running, so via a `bgpctl reload` after a config change.

This is the output from `bgpd -dv`:

```
startup
PF_KEY not available, disabling ipsec
rtr engine ready
session engine ready
rib_new: Adj-RIB-In -> 0
route decision engine ready
rib_new: Loc-RIB -> 1
listening on (unknown)
listening on (unknown)
SE reconfigured
neighbor 192.0.2.11: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::11: state change None -> Idle, reason: None
neighbor 192.0.2.21: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::21: state change None -> Idle, reason: None
neighbor 192.0.2.31: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::31: state change None -> Idle, reason: None
neighbor 192.0.2.41: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::41: state change None -> Idle, reason: None
neighbor 192.0.2.11: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::11: state change Idle -> Active, reason: Start
neighbor 192.0.2.21: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::21: state change Idle -> Active, reason: Start
neighbor 192.0.2.31: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::31: state change Idle -> Active, reason: Start
neighbor 192.0.2.41: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::41: state change Idle -> Active, reason: Start
RTR engine reconfigured
RDE reconfigured
running softreconfig in
softreconfig in done
RDE soft reconfiguration done
neighbor 192.0.2.11: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.11: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.11: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.11: sending IPv4 unicast EOR marker
neighbor 192.0.2.11: received IPv4 unicast EOR marker
neighbor 192.0.2.21: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.21: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.21: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.21: sending IPv4 unicast EOR marker
neighbor 192.0.2.21: received IPv4 unicast EOR marker
neighbor 192.0.2.31: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.31: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.31: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.31: sending IPv4 unicast EOR marker
neighbor 192.0.2.31: received IPv4 unicast EOR marker
neighbor 192.0.2.41: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.41: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.41: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.41: sending IPv4 unicast EOR marker
neighbor 192.0.2.41: received IPv4 unicast EOR marker
Rib Loc-RIB: neighbor 192.0.2.21 AS2: update 101.0.1.0/24 via 192.0.2.21
nexthop 192.0.2.21 now valid: directly connected: via 192.0.2.2
nexthop 192.0.2.21 update starting
nexthop 192.0.2.21 update finished
Rib Loc-RIB: neighbor 192.0.2.11 AS1: update 101.0.1.0/24 via 192.0.2.11
nexthop 192.0.2.11 now valid: directly connected: via 192.0.2.2
nexthop 192.0.2.11 update starting
nexthop 192.0.2.11 update finished
rereading config
SE reconfigured
RTR engine reconfigured
RDE reconfigured
RDE soft reconfiguration done





rereading config
SE reconfigured
RTR engine reconfigured
RDE reconfigured
RDE soft reconfiguration done
```

Random hypothesis: maybe the effect of `rde evaluate all` only applies to messages when they come in, and since in this case there are no new updates received by the daemon, the existing routes are not re-processed?

**Comment by cjeker** [comment] 2021-05-04 17:04
Yes, there  is no special reload handling for 'rde evaluate all' and a full session restart is needed for it to notice the change. I need to check what is required to make changes of 'rde evaluate' work via config reloads as well.

**Comment by cjeker** [comment] 2021-05-05 12:36
Diff to improve the reload behaviour sent to tech@ for review.

**Comment by pierky** [comment] 2021-05-08 13:51
> I managed to reproduce the withdraw issue and I sent a fix for that to tech@ mailing list.

I've tested a patched version of `bgpd` (I've applied the patches to the p0 and tested it via Docker containers), and although I was able to confirm the fix for the reload behaviour, unfortunately I was not able to validate the one for the withdrawal.

Same behaviour as the one originally reported:

- both routes are present:
```
bgpctl show rib detail`

BGP routing table entry for 101.0.1.0/24
    1 101
    Nexthop 192.0.2.11 (via 192.0.2.11) Neighbor 192.0.2.11 (192.0.2.11)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid, best
    Last update: 00:01:13 ago
    Communities: 0:3 0:4

BGP routing table entry for 101.0.1.0/24
    2 101 101 101 101
    Nexthop 192.0.2.21 (via 192.0.2.21) Neighbor 192.0.2.21 (192.0.2.21)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid
    Last update: 00:01:12 ago
```

- second best route announced to the client:
```
show rib out neighbor 192.0.2.31

flags: * = Valid, > = Selected, I = via IBGP, A = Announced,
       S = Stale, E = Error
origin validation state: N = not-found, V = valid, ! = invalid
origin: i = IGP, e = EGP, ? = Incomplete

flags ovs destination          gateway          lpref   med aspath origin
*       N 101.0.1.0/24         192.0.2.21        100     0 2 101 101 101 101 i
```

- session between the origin AS and the route-server client goes down and the route is withdrawn:

```
Rib Loc-RIB: neighbor 192.0.2.21 AS2: withdraw 101.0.1.0/24
```

```
bgpctl show rib detail

BGP routing table entry for 101.0.1.0/24
    1 101
    Nexthop 192.0.2.11 (via 192.0.2.11) Neighbor 192.0.2.11 (192.0.2.11)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid, best
    Last update: 00:02:19 ago
    Communities: 0:3 0:4
```

- the 2nd best route is still advertised to the other clients:
```
bgpctl show rib out neighbor 192.0.2.31

flags: * = Valid, > = Selected, I = via IBGP, A = Announced,
       S = Stale, E = Error
origin validation state: N = not-found, V = valid, ! = invalid
origin: i = IGP, e = EGP, ? = Incomplete

flags ovs destination          gateway          lpref   med aspath origin
*       N 101.0.1.0/24         192.0.2.21        100     0 2 101 101 101 101 i
```

Mind taking a look at the way I patched it?

```
cd /root/openbgpd-portable-6.9p0 && \
    ./autogen.sh && \
    ./configure --sysconfdir=/etc/bgpd && \
    cd src/bgpd/ && \
    patch -l < /root/issue23-rtr.patch && \
    patch -l < /root/issue21-rde_evaluate_all_withdrawal.patch && \
    patch -l < /root/issue21-rde_evaluate_all_reload.patch && \
    patch -l < /root/rtr-non-blocking-connect.patch && \
    cd ../../ && \
    make && \
    make install
```

The Docker image and Dockerfile can be found on DockerHub and GitHub, tag `6.9p0-patches`:
- image: https://hub.docker.com/layers/pierky/openbgpd/6.9p0-patches/images/sha256-2a9e0fda889e83d99d668321558ea66f8f91587a56f315282262f360e8e66701?context=repo
- Dockerfile and patch files I've used: https://github.com/pierky/dockerfiles/tree/master/openbgpd/6.9p0-patches

Full logs follow.

```
startup
PF_KEY not available, disabling ipsec
rtr engine ready
rib_new: Adj-RIB-In -> 0
route decision engine ready
session engine ready
rib_new: Loc-RIB -> 1
listening on (unknown)
listening on (unknown)
SE reconfigured
neighbor 192.0.2.11: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::11: state change None -> Idle, reason: None
neighbor 192.0.2.21: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::21: state change None -> Idle, reason: None
neighbor 192.0.2.31: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::31: state change None -> Idle, reason: None
neighbor 192.0.2.41: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::41: state change None -> Idle, reason: None
neighbor 192.0.2.11: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::11: state change Idle -> Active, reason: Start
neighbor 192.0.2.21: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::21: state change Idle -> Active, reason: Start
neighbor 192.0.2.31: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::31: state change Idle -> Active, reason: Start
neighbor 192.0.2.41: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::41: state change Idle -> Active, reason: Start
RTR engine reconfigured
RDE reconfigured
running softreconfig in
softreconfig in done
RDE soft reconfiguration done
neighbor 192.0.2.11: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.11: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.11: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.11: sending IPv4 unicast EOR marker
neighbor 192.0.2.11: received IPv4 unicast EOR marker
neighbor 192.0.2.21: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.21: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.21: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.21: sending IPv4 unicast EOR marker
neighbor 192.0.2.21: received IPv4 unicast EOR marker
rde_dump_ctx_new: no peer found for adj-rib-out



neighbor 192.0.2.31: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.31: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.31: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.31: sending IPv4 unicast EOR marker
neighbor 192.0.2.31: received IPv4 unicast EOR marker


neighbor 192.0.2.41: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.41: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.41: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.41: sending IPv4 unicast EOR marker
neighbor 192.0.2.41: received IPv4 unicast EOR marker
Rib Loc-RIB: neighbor 192.0.2.11 AS1: update 101.0.1.0/24 via 192.0.2.11
nexthop 192.0.2.11 now valid: directly connected: via 192.0.2.2
nexthop 192.0.2.11 update starting
nexthop 192.0.2.11 update finished
Rib Loc-RIB: neighbor 192.0.2.21 AS2: update 101.0.1.0/24 via 192.0.2.21
nexthop 192.0.2.21 now valid: directly connected: via 192.0.2.2
nexthop 192.0.2.21 update starting
nexthop 192.0.2.21 update finished
rereading config
SE reconfigured
RTR engine reconfigured
RDE reconfigured
RDE soft reconfiguration done
rereading config
SE reconfigured
RTR engine reconfigured
neighbor 2001:db8:1:1::41: rde evaluate change, reloading
neighbor 2001:db8:1:1::41: flushing Adj-RIB-Out
neighbor 2001:db8:1:1::31: rde evaluate change, reloading
neighbor 2001:db8:1:1::31: flushing Adj-RIB-Out
neighbor 2001:db8:1:1::21: rde evaluate change, reloading
neighbor 2001:db8:1:1::21: flushing Adj-RIB-Out
neighbor 2001:db8:1:1::11: rde evaluate change, reloading
neighbor 2001:db8:1:1::11: flushing Adj-RIB-Out
neighbor 192.0.2.41: rde evaluate change, reloading
neighbor 192.0.2.41: flushing Adj-RIB-Out
neighbor 192.0.2.31: rde evaluate change, reloading
neighbor 192.0.2.31: flushing Adj-RIB-Out
neighbor 192.0.2.21: rde evaluate change, reloading
neighbor 192.0.2.21: flushing Adj-RIB-Out
neighbor 192.0.2.11: rde evaluate change, reloading
neighbor 192.0.2.11: flushing Adj-RIB-Out
RDE reconfigured
softreconfig in done
RDE soft reconfiguration done
neighbor 192.0.2.11: sending IPv4 unicast EOR marker
neighbor 192.0.2.41: sending IPv4 unicast EOR marker
neighbor 192.0.2.31: sending IPv4 unicast EOR marker
neighbor 192.0.2.21: sending IPv4 unicast EOR marker









rereading config
SE reconfigured
RTR engine reconfigured
RDE reconfigured
RDE soft reconfiguration done






Rib Loc-RIB: neighbor 192.0.2.21 AS2: withdraw 101.0.1.0/24
```

Thanks

**Comment by cjeker** [comment] 2021-05-10 11:04
I have a regress test in OpenBSD that does exactly the same with exabgp and it works there.
Not entirely sure where your problem is, form a quick look I think the patches should be applied correctly but I did not verify that. Docker is just not my thing.

**Comment by cjeker** [comment] 2021-05-11 08:31
Yes, in your case you only reload and then do a withdraw. In that case rde_evaluate_all() is actually returning the wrong result and so the system thinks it has no peers that evaluate all prefixes.
The problem is that rde_eval_all is tracked in the wrong spot. The following patch should fix this... hopefully.

[bdiff.txt](https://github.com/openbgpd-portable/openbgpd-portable/files/6457656/bdiff.txt)

**Comment by pierky** [comment] 2021-05-11 18:52
> The problem is that rde_eval_all is tracked in the wrong spot. The following patch should fix this... hopefully.
> 
> [bdiff.txt](https://github.com/openbgpd-portable/openbgpd-portable/files/6457656/bdiff.txt)

It fixed the issue as far as I can see from my test suite.
Thanks a lot.

Is there any plan to ship a new release of bgpd soon or should we wait for the next OpenBSD one to have the patches in?

**Comment by cjeker** [comment] 2021-05-27 08:48
I just committed the fixes to -current. My plan is to release 6.9p1 early June.

**Comment by cjeker** [comment] 2021-06-07 07:59
The new 7.0 release should have all required fixes.

**Closed by cjeker** 2021-06-07 07:59 UTC
