### ISSUE TITLE
tcp md5sig on linux

### ISSUE THREAD

**Issue by bilias** [openbgpd-portable/openbgpd-portable#79] opened 2024-06-01 12:28 UTC
Is tcp md5sig not supported on Linux?

tcpdump shows:
03:27:00.333557 IP (tos 0x0, ttl 63, id 32056, offset 0, flags [DF], proto TCP (6), length 72)
    xx.xx.xx.xx.31986 > yy.yy.yy.yy.179: Flags [S], cksum 0x4a7a (correct), seq 2925962972, win 29200, options [nop,nop,md5 shared secret not supplied with -M, can't check - a1c7c71f69f8bb9e0df37a843f99985f,mss 1460,nop,nop,sackOK,nop,wscale 0], length 0

syslog:
Jun  2 03:27:00 kernel: TCP: Unexpected MD5 Hash found for xx.xx.xx.xx.31986-->yy.yy.yy.yy.179 [S] 

both ends are Linux, run openbgpd-8.4 and have in kernel support
CONFIG_TCP_MD5SIG=y

If I disable md5sig then everything works.

Linux <-> OpenBSD is fine

Edit:
The problem seems to be with one of them having a newer Linux kernel

Linux 6.8.10 <-> Linux 4.18

xx.xx.xx.xx is the IP of Linux 4.18
yy.yy.yy.yy is the IP of Linux 6.8

I've found this one, maybe it's related:
https://lists.linaro.org/archives/list/linux-kselftest-mirror@lists.linaro.org/thread/4IG5H676IPHPH7QA42WDLEARDW6I3U2U/

**Comment by cjeker** [comment] 2024-06-18 10:08
There is an issue with at least alpine linux where tcp md5sum is disabled because the configure test is not finding the required struct. This issue should be solved by 5d1c8b0c85f3a6ae41fdd970238b3a3337af6a46.

Please check the configure output if you see:
```
checking for struct tcp_md5sig.tcpm_key... yes
```
This is needed to compile `pfkey-linux.c` which has the tcp md5 support.

Please report if the above commit fixes your issue (also please include the configure and build log if not).

**Comment by bilias** [comment] 2024-06-18 13:10
No this, didn't make any change.
Only change is that now it required automake to be installed.

With and without that option config.log shows
```
configure:13591: checking for struct tcp_md5sig.tcpm_key
configure:13591: gcc -c -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  conftest.c >&5
configure:13591: $? = 0
configure:13591: result: yes
```

This is Rocky 9 / 5.14.0-427.20.1.el9_4.x86_64
I'm trying to connect with Fedora 40 / 6.9.3-200.fc40.x86_64

I'm attaching config.log and the tee from build
[config.log](https://github.com/user-attachments/files/15887077/config.log)
[build.log](https://github.com/user-attachments/files/15887078/build.log)

**Comment by cjeker** [comment] 2024-06-18 13:36
I tested this with a Debian 12 and Alpine Edge and there the connection works without a hitch.
So this is not a Linux issue per se. The syslog message is from your Fedora install?
It indicates that the listening socket on yy.yy.yy.yy.179 does not have the tcp md5 key loaded.
Not sure what is going on there.
Is there anything in `bgpd -dvv` output?

**Comment by cjeker** [comment] 2024-06-18 15:42
So I can confirm that something in Fedora 40 with kernel 6.9.4 is not working.
While outgoing connections work with TCP MD5 it does not work on the listening socket.
Unclear what is going on here. This works both with Debian12 `Linux 6.1.0-21-amd64 ` and Alpine `Linux 6.6.33-0-lts`.

Is this a regression introduce into the 6.8 line of Linux?

**Comment by bilias** [comment] 2024-06-18 16:01
I'm new to openbgpd so I can't tell if it's a new regression.
Playing with this right now.

When the old kernel linux is in passive mode and the connection is initiated from Fedora (6.8/6.9), I see nothing on the logs of Fedora.

When the old kernel linux actively connects to Fedora I see 
Unexpected MD5 Hash found for xx.xxx
I believe it's a kernel message printed on syslog of Fedora.

I have the same problem between other kernels as well
Rocky 8 (4.18.0-553.5.1.el8_10.x86_64) <-> Rocky 9 (5.14.0-427.20.1.el9_4.x86_64)
Here I see no kernel messages on syslog but with tcp md5sig does not Established.
If I remove this, then again everything works.

Don't if it's something backported from 6.8

When  4.18.0-553.5.1.el8_10 is passive and md5 on
and 5.14.0-427.20.1.el9_4 is active and md5 off the setup also goes to Established

The other way around it does not work.
It's not a firewall issue, I can telnet on bgp port both ways.

**Comment by bilias** [comment] 2024-06-18 16:20
This looks interesting:
https://lore.kernel.org/lkml/20230614230947.3954084-1-dima@arista.com/T/
search for bgp

**Comment by cjeker** [comment] 2024-06-18 20:12
What exact kernel versions are used in Rocky 8 and 9? I doubt that those are really 4.18 and 5.14 kernels...
I'm  not into Linux, my assumption is that something like the mentioned TCP-AO diff broke TCP MD5 on listening sockets.
So it would be good to know which Linux kernel introduced the regression and then cross check if that fits with the TCP-AO work.

**Comment by bilias** [comment] 2024-06-19 04:47
I've tried this little demo tcp_md5sig server/client
https://gist.github.com/tjs-w/57b99c2a7a50fff5dc3f (modified to INET instead of INET6)

and it worked fine between Fedora 40 and Rocky (Redhat 9) in both ways being client or server

**Comment by bilias** [comment] 2024-06-19 06:42
The problem seems to be in in tcp_md5_prep_listener()
```
      if (p->conf.auth.method == AUTH_MD5SIG) {
         if (listener_match_peer(la, p) == 0) {
            continue;
         }
```
We never reach install_tcp_md5() as there is a match there

**Comment by cjeker** [comment] 2024-06-19 08:39
> The problem seems to be in in tcp_md5_prep_listener()
> 
> https://github.com/openbgpd-portable/openbgpd-portable/blob/5d1c8b0c85f3a6ae41fdd970238b3a3337af6a46/src/bgpd/pfkey-linux.c#L154-L173
> 
> We never reach install_tcp_md5()

No, this is not true. At least in my configs I do reach install_tcp_md5() there just fine.
It also makes no sense why this code works on a Linux 6.6 kernel but fails on a 6.8 one. It is the same code.
As mentioned Linux introduced a regression into their TCP MD5 support.

**Comment by bilias** [comment] 2024-06-19 08:46
> No, this is not true. At least in my configs I do reach install_tcp_md5() there just fine. It also makes no sense why this code works on a Linux 6.6 kernel but fails on a 6.8 one. It is the same code. As mentioned Linux introduced a regression into their TCP MD5 support.

Claudio, try to put neighbor inside a group.

I just tried it outside of a group and it also called install_tcp_md5()

But when inside a group it did not.

**Comment by bilias** [comment] 2024-06-19 09:05
And we reach it cause of this, which seems strange
```
   if (sa == NULL) {
      /* undefined bind address will match any listener */
      log_warnx("ADDRESS NULL");
      return 1;
   }
```

**Comment by cjeker** [comment] 2024-06-19 10:35
Please share your config so I can reproduce.
The above code is for the case where in the config no `local-address` has been set on the neighbor. In that case any local address is allowed and so the MD5 key needs to be installed on all listening sockets.
I think we should actually install the keys on all listening sockets of the right AF and not look at the local bind address at all.

Changing that still does not solve the issue that they introduced in the linux kernel.
The actual problem is that on a listening socket you can no longer install a TCP MD5 key without specifying the remote port. This is a clear regression on their side and you need to open a bug report there.

The gist code from above works because it requires you to define both the server listen port and the client connect port.
This only works if the client binds to that port before the connect. Nobody does that, all BGP server will connect with a unknown high TCP port to port 179.

**Comment by bilias** [comment] 2024-06-19 11:04
Yes, problem was not group, it was `local-address` which was defined.
In my group setup I had local-address, but when I copied neighbor outside of group I didn't put local-address inside.

So when I set local-address it fails.

Forget about the git code. It also sets remote IP on setsockopt()
I don't believe client port is needed in that code, at least on server side.

My minimal test config is like this:

ASN="65002"
testASN="65002"

myIP="10.0.0.1"
remoteIP="10.0.0.2"
remotePort="1234"

# global configuration
AS $ASN
router-id $myIP

listen on $myIP port 179
#listen on 0.0.0.0 port 179

socket "/run/bgpd/bgpd.sock2.0"
fib-update no

neighbor $remoteIP {
      remote-as $testASN
      local-address $myIP
      port $remotePort
      tcp md5sig password wQaK7CzUOHLiS3sdMwwL
}

allow from any
allow to any

**Comment by cjeker** [comment] 2024-06-19 13:14
See pull-request #80 which should fix the problem with local-address vs listen address.

**Comment by cjeker** [comment] 2024-06-19 14:28
> So I can confirm that something in Fedora 40 with kernel 6.9.4 is not working. While outgoing connections work with TCP MD5 it does not work on the listening socket. Unclear what is going on here. This works both with Debian12 `Linux 6.1.0-21-amd64 ` and Alpine `Linux 6.6.33-0-lts`.
> 
> Is this a regression introduce into the 6.8 line of Linux?

No, it is me not disabling the stupid `firewalld` on my throw away VM.
With the firewall disabled all works.

**Comment by cjeker** [comment] 2024-06-19 14:29
Fix merged.

**Closed by cjeker** 2024-06-19 14:29 UTC

**Comment by 0x7f454c46** [comment] 2024-06-28 13:44
To confirm, as far as I understand you don't observe any regressions on TCP-MD5, right?
